### ISSUE TITLE
PuGenerator does not exist

### ISSUE THREAD

**Issue by PersonaA** [betterobjects/activeql#1]
`express/__activeql/bin/activeql-app.ts`:

```
import { DomainDefinition, MongoDbDataStore, ActiveQLServer, Runtime, PuGenerator } from 'activeql-server';
...
export const activeqlUml = () => new PuGenerator( domainDefinition.getResolvedConfiguration() ).generate();
```

But there is no `PuGenerator` in `activeql-server`.

**Comment by thorek** [comment]
It's actually something that shouldn't be in the master branch. You can safely delete `./express/__activeql` and use `./express/activeql`. Thanks for pointing out. It will be removed.

If you want to develop with ActiveQL you should either start with the starter-application [https://github.com/betterobjects/activeql-starter](https://github.com/betterobjects/activeql-starter) or use the generator `npx betterobjects/activeql-generator my-activeql`

The "shell" applications in this repo are for development purposes. 

Hope this helps.

**Comment by PersonaA** [comment]
> If you want to develop with ActiveQL you should either start with the starter-application https://github.com/betterobjects/activeql-starter or use the generator `npx betterobjects/activeql-generator my-activeql`

I tried both and found this issue with `PuGenerator` in both starter-application and generator.

**Comment by thorek** [comment]
Yes, the recent update wasn't live. It's updated now. 

If you do not need to generate a UML class diagram from your entities and types,  it's also safe to delete this part from the `./activeql-app.ts`

**Comment by thorek** [comment]
I just checked a newly created app from the generator and it works. Sorry for the inconvenience! The UML and typed-classes feature was added recently and is still under development.
